<h1 style="text-align: center;"> TC3006C: Inteligencia artificial avanzada para la ciencia de datos I</h1>
<p></p>
<div style="text-align: center;"> <em>Dummy variables</em> </div>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.formula.api as smf
from scipy import stats
from sklearn.preprocessing import PolynomialFeatures

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [2]:
# Loading data

url = 'https://drive.google.com/file/d/14cl3aR2tkp3BzpUQqpeDZ7j6X9MEQFX7/view?usp=sharing'
file_id = url.split('/')[-2]
dwn_url = 'https://drive.google.com/uc?id=' + file_id

main_cols = ['Calories','Carbohydrates','Total_Fat','Protein','Sodium','Sugars']

tmp = pd.read_csv(dwn_url)
tmp = tmp.rename(columns={'Total Fat':'Total_Fat'})

tmp.head(2)

,Category,Item,Serving Size,Calories,Calories from Fat,Total_Fat,Total Fat (% Daily Value),Saturated Fat,Saturated Fat (% Daily Value),Trans Fat,...,Carbohydrates,Carbohydrates (% Daily Value),Dietary Fiber,Dietary Fiber (% Daily Value),Sugars,Protein,Vitamin A (% Daily Value),Vitamin C (% Daily Value),Calcium (% Daily Value),Iron (% Daily Value)
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300,120,13.0,20,5.0,25,0.0,...,31,10,4,17,3,17,10,0,25,15
1,Breakfast,Egg White Delight,4.8 oz (135 g),250,70,8.0,12,3.0,15,0.0,...,30,10,4,17,3,18,6,0,25,8

In [ ]:
tmp['Category'].value_counts()

Coffee & Tea          95
Breakfast             42
Smoothies & Shakes    28
Chicken & Fish        27
Beverages             27
Beef & Pork           15
Snacks & Sides        13
Desserts               7
Salads                 6
Name: Category, dtype: int64

In [3]:
tmp['Item'].value_counts()

Egg McMuffin                                        1
Nonfat Latte (Small)                                1
Nonfat Latte (Large)                                1
Nonfat Caramel Latte (Small)                        1
Nonfat Caramel Latte (Medium)                       1
                                                   ..
Chipotle BBQ Snack Wrap (Grilled Chicken)           1
Honey Mustard Snack Wrap (Crispy Chicken)           1
Honey Mustard Snack Wrap (Grilled Chicken)          1
Ranch Snack Wrap (Crispy Chicken)                   1
McFlurry with Reese's Peanut Butter Cups (Snack)    1
Name: Item, Length: 260, dtype: int64

## Dummy variables

Hay diferentes mÃ©todos para transformar las variables categÃ³ricas a numÃ©ricas para usarlas en un modelo. 

* Label encoding: a cada categorÃ­a diferente en la columna se asocia una etiqueta numÃ©rica. En sklearn, "LabelEncoder" asigna un valor nÃºmerico creciente a las categorÃ­as por orden alfabÃ©tico. Si no hay jerarquÃ­a en las variables categÃ³ricas, el "LabelEncoder" asigna un orden jerÃ¡rquico segÃºn el orden alfabÃ©tico. Esto podrÃ­a ser un problema si el modelo "detecta" el order jerÃ¡rquico que en realidad no existe.

* One Hot Encoding: se crean dummy variables para cada categorÃ­a de la(s) variable(s) categÃ³rica(s). Se puede hacer con la librerÃ­a sklearn con "One Hot Encoder", o con la librerÃ­a pandas con "get_dummies".

In [ ]:
dummies = pd.get_dummies(tmp['Category'])
#dummies = pd.get_dummies(tmp['Category'], drop_first=True)
dummies.head(3)

,Beef & Pork,Beverages,Breakfast,Chicken & Fish,Coffee & Tea,Desserts,Salads,Smoothies & Shakes,Snacks & Sides
0,0,0,1,0,0,0,0,0,0
1,0,0,1,0,0,0,0,0,0
2,0,0,1,0,0,0,0,0,0

In [ ]:
tmp['Category'].unique()

array(['Breakfast', 'Beef & Pork', 'Chicken & Fish', 'Salads',
       'Snacks & Sides', 'Desserts', 'Beverages', 'Coffee & Tea',
       'Smoothies & Shakes'], dtype=object)

In [ ]:
pd.concat([tmp.drop(columns=['Category']), dummies], axis=1).head(3)

,Item,Serving Size,Calories,Calories from Fat,Total_Fat,Total Fat (% Daily Value),Saturated Fat,Saturated Fat (% Daily Value),Trans Fat,Cholesterol,...,Iron (% Daily Value),tCalo,Beverages,Breakfast,Chicken & Fish,Coffee & Tea,Desserts,Salads,Smoothies & Shakes,Snacks & Sides
0,Egg McMuffin,4.8 oz (136 g),300,120,13.0,20,5.0,25,0.0,260,...,15,44.840921,0,1,0,0,0,0,0,0
1,Egg White Delight,4.8 oz (135 g),250,70,8.0,12,3.0,15,0.0,25,...,8,40.209733,0,1,0,0,0,0,0,0
2,Sausage McMuffin,3.9 oz (111 g),370,200,23.0,35,8.0,42,0.0,45,...,10,50.807978,0,1,0,0,0,0,0,0

In [ ]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
tmp['Category_labelEnc']=label_encoder.fit_transform(tmp['Category'])

In [ ]:
tmp[['Category','Category_labelEnc']].head(50)

       Category  Category_labelEnc
0     Breakfast                  2
1     Breakfast                  2
2     Breakfast                  2
3     Breakfast                  2
4     Breakfast                  2
5     Breakfast                  2
6     Breakfast                  2
7     Breakfast                  2
8     Breakfast                  2
9     Breakfast                  2
10    Breakfast                  2
11    Breakfast                  2
12    Breakfast                  2
13    Breakfast                  2
14    Breakfast                  2
15    Breakfast                  2
16    Breakfast                  2
17    Breakfast                  2
18    Breakfast                  2
19    Breakfast                  2
20    Breakfast                  2
21    Breakfast                  2
22    Breakfast                  2
23    Breakfast                  2
24    Breakfast                  2
25    Breakfast                  2
26    Breakfast                  2
27    Breakfast                  2
28    Breakfast                  2
29    Breakfast                  2
30    Breakfast                  2
31    Breakfast                  2
32    Breakfast                  2
33    Breakfast                  2
34    Breakfast                  2
35    Breakfast                  2
36    Breakfast                  2
37    Breakfast                  2
38    Breakfast                  2
39    Breakfast                  2
40    Breakfast                  2
41    Breakfast                  2
42  Beef & Pork                  0
43  Beef & Pork                  0
44  Beef & Pork                  0
45  Beef & Pork                  0
46  Beef & Pork                  0
47  Beef & Pork                  0
48  Beef & Pork                  0
49  Beef & Pork                  0